[workspace]
resolver = "3"
members = ["mcumgr-toolkit", "mcumgr-toolkit-python", "mcumgrctl"]

[workspace.package]
version = "0.17.1"
authors = ["Finomnis <finomnis@gmail.com>"]
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Finomnis/mcumgr-toolkit"
description = "Software suite for Zephyr's MCUmgr protocol"
keywords = ["zephyr", "mcumgr", "smp"]

exclude = ["/.gitignore", "/.github/"]

[workspace.dependencies]
mcumgr-toolkit = { version = "0.17.1", path = "./mcumgr-toolkit" }
serialport = { version = "4.9.0", default-features = false }
thiserror = "2.0.20"
miette = "7.6.0"
rand = "0.10.1"
base64 = "0.23.1"
crc = "3.4.0"
sha2 = "0.11.0"
ringbuf = "0.5.0"
serde = "1.0.228"
serde_bytes = "0.11.19"
serde_json = "1.0.145"
serde_repr = "0.1.20"
ciborium = "0.2.2"
log = "0.4.34"
env_logger = "0.11.10"
clap = "4.6.0"
clap_mangen = "0.3.0"
clap_complete = "4.6.3"
strum = "0.28.0"
indicatif = "0.18.3"
indicatif-log-bridge = "0.2.3"
chrono = "0.4.42"
pyo3 = "0.29.0"
pyo3-stub-gen = "0.23.0"
pyo3-log = "0.13.3"
serde-pyobject = "0.8.0"
hex = "0.4.3"
regex = "1.12.2"
console = "0.16.2"
polonius-the-crab = "0.5.0"
pretty-hex = "0.4.2"
btleplug = "0.13.1"
tokio = "1.53.1"
futures = "0.3.34"
uuid = "1.26.1"
either = "1.15.0"
dbus = "0.9.12"
socket2 = "0.6.5"
libc = "0.2.189"

[profile.release]
strip = true
lto = true
codegen-units = 1
