# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import datetime
import enum
import ipaddress
import typing
__all__ = [
    "FileChecksum",
    "FileChecksumDataFormat",
    "FileChecksumProperties",
    "FileStatus",
    "GroupDetails",
    "ImageState",
    "MCUmgrClient",
    "MCUmgrParameters",
    "McubootImageInfo",
    "MemoryPoolStatistics",
    "SettingData",
    "SlotInfoImage",
    "SlotInfoImageSlot",
    "TaskStatistics",
    "mcuboot_get_image_info",
]

@typing.final
class FileChecksum:
    r"""
    Return value of `MCUmgrClient.fs_file_checksum`.
    """
    @property
    def type(self) -> builtins.str:
        r"""
        type of hash/checksum that was performed
        """
    @property
    def offset(self) -> builtins.int:
        r"""
        offset that hash/checksum calculation started at
        """
    @property
    def length(self) -> builtins.int:
        r"""
        length of input data used for hash/checksum generation (in bytes)
        """
    @property
    def output(self) -> bytes:
        r"""
        output hash/checksum
        """

@typing.final
class FileChecksumProperties:
    r"""
    Properties of a hash/checksum algorithm
    """
    @property
    def format(self) -> FileChecksumDataFormat:
        r"""
        format that the hash/checksum returns
        """
    @property
    def size(self) -> builtins.int:
        r"""
        size (in bytes) of output hash/checksum response
        """

@typing.final
class FileStatus:
    r"""
    Return value of `MCUmgrClient.fs_file_status`.
    """
    @property
    def length(self) -> builtins.int:
        r"""
        length of file (in bytes)
        """

@typing.final
class GroupDetails:
    r"""
    Details about an MCUmgr group
    """
    @property
    def group(self) -> builtins.int:
        r"""
        the group ID of the MCUmgr command group
        """
    @property
    def name(self) -> typing.Optional[builtins.str]:
        r"""
        the name of the MCUmgr command group
        """
    @property
    def handlers(self) -> typing.Optional[builtins.int]:
        r"""
        the number of handlers that the MCUmgr command group supports
        """

@typing.final
class ImageState:
    r"""
    The state of an image slot
    """
    @property
    def image(self) -> builtins.int:
        r"""
        image number
        """
    @property
    def slot(self) -> builtins.int:
        r"""
        slot number within “image”
        """
    @property
    def version(self) -> builtins.str:
        r"""
        string representing image version, as set with `imgtool`
        """
    @property
    def hash(self) -> typing.Optional[bytes]:
        r"""
        Hash of the image header and body
        
        Note that this will not be the same as the SHA256 of the whole file, it is the field in the
        MCUboot TLV section that contains a hash of the data which is used for signature
        verification purposes.
        """
    @property
    def bootable(self) -> builtins.bool:
        r"""
        true if image has bootable flag set
        """
    @property
    def pending(self) -> builtins.bool:
        r"""
        true if image is set for next swap
        """
    @property
    def confirmed(self) -> builtins.bool:
        r"""
        true if image has been confirmed
        """
    @property
    def active(self) -> builtins.bool:
        r"""
        true if image is currently active application
        """
    @property
    def permanent(self) -> builtins.bool:
        r"""
        true if image is to stay in primary slot after the next boot
        """

@typing.final
class MCUmgrClient:
    r"""
    A high-level client for Zephyr's MCUmgr SMP functionality
    """
    @staticmethod
    def serial(serial: builtins.str, baud_rate: builtins.int = 115200, timeout_ms: builtins.int = 1000) -> MCUmgrClient:
        r"""
        Creates a new serial port based Zephyr MCUmgr SMP client.
        
        ### Arguments
        
        * `serial` - The identifier of the serial device. (Windows: `COMxx`, Linux: `/dev/ttyXX`)
        * `baud_rate` - The baud rate of the serial port.
        * `timeout_ms` - The communication timeout, in ms.
        """
    @staticmethod
    def usb_serial(identifier: builtins.str, baud_rate: builtins.int = 115200, timeout_ms: builtins.int = 1000) -> MCUmgrClient:
        r"""
        Creates a Zephyr MCUmgr SMP client based on a USB serial port identified by VID:PID.
        
        Useful for programming many devices in rapid succession, as Windows usually
        gives each one a different COMxx identifier.
        
        ### Arguments
        
        * `identifier` - A regex that identifies the device.
        * `baud_rate` - The baud rate the port should operate at.
        * `timeout_ms` - The communication timeout, in ms.
        
        ### Identifier examples
        
        - `1234:89AB` - Vendor ID 1234, Product ID 89AB. Will fail if product has multiple serial ports.
        - `1234:89AB:12` - Vendor ID 1234, Product ID 89AB, Interface 12.
        - `1234:.*:[2-3]` - Vendor ID 1234, any Product Id, Interface 2 or 3.
        """
    @staticmethod
    def udp(host: typing.Union[builtins.str, ipaddress.IPv4Address | ipaddress.IPv6Address], port: builtins.int = 1337, timeout_ms: builtins.int = 1000) -> MCUmgrClient:
        r"""
        Creates a new UDP-based Zephyr MCUmgr SMP client.
        
        ### Arguments
        
        * `host` - The UDP endpoint IP address or hostname.
        * `port` - The UDP endpoint port number.
        * `timeout_ms` - The communication timeout, in ms.
        """
    @staticmethod
    def ethernet(iface: builtins.str, mac: builtins.str, timeout_ms: builtins.int = 1000) -> MCUmgrClient:
        r"""
        Creates a new raw Ethernet based Zephyr MCUmgr SMP client.
        
        Only supported on Linux. Requires the `CAP_NET_RAW` capability.
        
        ### Arguments
        
        * `iface` - The local network interface the device is connected to, e.g. `eth0`.
        * `mac` - The MAC address of the device, e.g. `02:00:00:00:00:01`.
        * `timeout_ms` - The communication timeout, in ms.
        """
    @staticmethod
    def ble(identifier: builtins.str, timeout_ms: builtins.int = 1000) -> MCUmgrClient:
        r"""
        Creates a Zephyr MCUmgr SMP client based on a BLE connection.
        
        ### Arguments
        
        * `identifier` - An OS dependent identifier for BLE devices.
        * `timeout_ms` - The communication timeout, in ms.
        
        On most operating systems, the identifier is the BLE device MAC address.
        The notable exception is MacOS/iOS where it is the device UUID.
        """
    def set_frame_size(self, smp_frame_size: builtins.int) -> None:
        r"""
        Configures the maximum SMP frame size that we can send to the device.
        
        Must not exceed [`MCUMGR_TRANSPORT_NETBUF_SIZE`](https://github.com/zephyrproject-rtos/zephyr/blob/v4.2.1/subsys/mgmt/mcumgr/transport/Kconfig#L40),
        otherwise we might crash the device.
        """
    def use_auto_frame_size(self) -> None:
        r"""
        Configures the maximum SMP frame size that we can send to the device automatically
        by reading the value of [`MCUMGR_TRANSPORT_NETBUF_SIZE`](https://github.com/zephyrproject-rtos/zephyr/blob/v4.2.1/subsys/mgmt/mcumgr/transport/Kconfig#L40)
        from the device.
        """
    def set_timeout_ms(self, timeout_ms: builtins.int) -> None:
        r"""
        Changes the communication timeout.
        
        When the device does not respond to packets within the set
        duration, an error will be raised.
        """
    def set_retries(self, retries: builtins.int) -> None:
        r"""
        Changes the retry amount.
        
        When the device encounters a transport error, it will retry
        this many times until giving up.
        """
    def check_connection(self) -> None:
        r"""
        Checks if the device is alive and responding.
        
        Runs a simple echo with random data and checks if the response matches.
        
        Raises an error if the device is not alive and responding.
        """
    def firmware_update(self, firmware: bytes, checksum: typing.Optional[builtins.str | builtins.bytes] = None, bootloader_type: typing.Optional[typing.Literal['MCUboot']] = None, skip_reboot: builtins.bool = False, force_confirm: builtins.bool = False, upgrade_only: builtins.bool = False, progress: typing.Optional[collections.abc.Callable[[builtins.str, typing.Optional[builtins.tuple[builtins.int, builtins.int]]], None]] = None) -> None:
        r"""
        High-level firmware update routine.
        
        ### Arguments
        
        * `firmware` - The firmware image data.
        * `checksum` - SHA256 of the firmware image. Optional.
        * `bootloader_type` - The type of bootloader. Auto-detect bootloader if missing.
        * `skip_reboot` - Do not reboot device after the update.
        * `force_confirm` - Skip test boot and confirm directly.
        * `upgrade_only` - Prevent firmware downgrades.
        * `progress` - A callback that receives progress updates.
        """
    def os_echo(self, msg: builtins.str) -> builtins.str:
        r"""
        Sends a message to the device and expects the same message back as response.
        
        This can be used as a sanity check for whether the device is connected and responsive.
        """
    def os_task_statistics(self) -> builtins.dict[builtins.str, TaskStatistics]:
        r"""
        Queries live task statistics
        
        ### Note
        
        Converts `stkuse` and `stksiz` to bytes.
        Zephyr originally reports them as number of 4 byte words.
        
        ### Return
        
        A map of task names with their respective statistics
        """
    def os_memory_pool_statistics(self) -> builtins.dict[builtins.str, MemoryPoolStatistics]:
        r"""
        Queries live memory pool statistics
        
        ### Return
        
        A map of memory pool names with their respective statistics
        """
    def os_set_datetime(self, datetime: datetime.datetime) -> None:
        r"""
        Sets the RTC of the device to the given datetime.
        
        Uses the contained local time and discards timezone information.
        """
    def os_get_datetime(self) -> datetime.datetime:
        r"""
        Retrieves the device RTC's datetime.
        
        Will not contain timezone information.
        """
    def os_system_reset(self, force: builtins.bool = False, boot_mode: typing.Optional[builtins.int] = None) -> None:
        r"""
        Issues a system reset.
        
        ### Arguments
        
        * `force` - Issues a force reset.
        * `boot_mode` - Overwrites the default boot mode.
        
        Known `boot_mode` values:
        * `0` - Normal system boot
        * `1` - Bootloader recovery mode
        
        Note that `boot_mode` only works if [`MCUMGR_GRP_OS_RESET_BOOT_MODE`](https://docs.zephyrproject.org/latest/kconfig.html#CONFIG_MCUMGR_GRP_OS_RESET_BOOT_MODE) is enabled.
        """
    def os_mcumgr_parameters(self) -> MCUmgrParameters:
        r"""
        Fetch parameters from the MCUmgr library
        """
    def os_application_info(self, format: typing.Optional[builtins.str] = None) -> builtins.str:
        r"""
        Fetch information on the running image
        
        Similar to Linux's `uname` command.
        
        ### Arguments
        
        * `format` - Format specifier for the returned response
        
        For more information about the format specifier fields, see
        the [SMP documentation](https://docs.zephyrproject.org/latest/services/device_mgmt/smp_groups/smp_group_0.html#os-application-info-request).
        """
    def os_bootloader_info(self) -> typing.Any:
        r"""
        Fetch information on the device's bootloader
        """
    def image_get_state(self) -> builtins.list[ImageState]:
        r"""
        Obtain a list of images with their current state.
        """
    def image_set_state(self, hash: typing.Optional[builtins.str | builtins.bytes] = None, confirm: builtins.bool = False) -> builtins.list[ImageState]:
        r"""
        Modify the current image state and return the new state
        
        ### Arguments
        
        * `hash` - the hash id of the image. See `mcuboot_get_image_info`.
        * `confirm` - mark the given image as 'confirmed'
        
        If `confirm` is `false`, perform a test boot with the given image and revert upon hard reset.
        
        If `confirm` is `true`, boot to the given image and mark it as `confirmed`. If `hash` is omitted,
        confirm the currently running image.
        
        Note that `hash` will not be the same as the SHA256 of the whole firmware image,
        it is the field in the MCUboot TLV section that contains a hash of the data
        which is used for signature verification purposes.
        """
    def image_upload(self, data: bytes, image: typing.Optional[builtins.int] = None, checksum: typing.Optional[builtins.str | builtins.bytes] = None, upgrade_only: builtins.bool = False, progress: typing.Optional[collections.abc.Callable[[builtins.int, builtins.int], None]] = None) -> None:
        r"""
        Upload a firmware image to an image slot.
        
        ### Note
        
        This only uploads the image to a slot on the device, it has to be activated
        through `image_set_state` for an actual update to happen.
        
        For a full firmware update algorithm in a single step, see `firmware_update`.
        
        ### Arguments
        
        * `data` - The firmware image data
        * `image` - Selects target image on the device. Defaults to `0`.
        * `checksum` - The SHA256 checksum of the image. If missing, will be computed from the image data.
        * `upgrade_only` - If true, allow firmware upgrades only and reject downgrades.
        * `progress` - A callable object that takes (transmitted, total) values as parameters.
                       Any return value is ignored. Raising an exception aborts the operation.
        
        ### Performance
        
        Uploading files with Zephyr's default parameters is slow.
        You want to increase [`MCUMGR_TRANSPORT_NETBUF_SIZE`](https://github.com/zephyrproject-rtos/zephyr/blob/v4.2.1/subsys/mgmt/mcumgr/transport/Kconfig#L40)
        to maybe `4096` and then enable larger chunking through either `set_frame_size`
        or `use_auto_frame_size`.
        """
    def image_erase(self, slot: typing.Optional[builtins.int] = None) -> None:
        r"""
        Erase image slot on target device.
        
        ### Arguments
        
        * `slot` - The slot ID of the image to erase. Slot `1` if omitted.
        """
    def image_slot_info(self) -> builtins.list[SlotInfoImage]:
        r"""
        Obtain a list of available image slots.
        """
    def stats_get_group_data(self, name: builtins.str) -> builtins.dict[builtins.str, builtins.int]:
        r"""
        Query the current values of a given stats group
        
        ### Arguments
        
        * `name` - The name of the group. See `stats_list_groups`.
        """
    def stats_list_groups(self) -> builtins.list[builtins.str]:
        r"""
        Query the list of available stats groups
        """
    def settings_read(self, name: builtins.str) -> bytes:
        r"""
        Read a setting from the device.
        
        ### Arguments
        
        * `name` - The name of the setting.
        
        ### Return
        
        The value of the setting, as raw bytes.
        
        Note that the underlying data type cannot be specified through this and must be known by the client.
        """
    def settings_read_ext(self, name: builtins.str, max_size: typing.Optional[builtins.int] = None) -> SettingData:
        r"""
        Read a setting from the device.
        
        Extended version.
        
        ### Arguments
        
        * `name` - The name of the setting.
        * `max_size` - Optional maximum size of data to return.
        """
    def settings_write(self, name: builtins.str, value: bytes) -> None:
        r"""
        Write a setting to the device.
        
        ### Arguments
        
        * `name` - The name of the setting.
        * `value` - The value of the setting.
        """
    def settings_delete(self, name: builtins.str) -> None:
        r"""
        Delete a setting from the device.
        
        ### Arguments
        
        * `name` - The name of the setting.
        """
    def settings_commit(self) -> None:
        r"""
        Commit all modified settings on the device.
        """
    def settings_load(self) -> None:
        r"""
        Load settings from persistent storage.
        """
    def settings_save(self, name: typing.Optional[builtins.str] = None) -> None:
        r"""
        Save settings to persistent storage.
        
        ### Arguments
        
        * `name` - Only persist the subtree with the given name.
        """
    def fs_file_download(self, name: builtins.str, progress: typing.Optional[collections.abc.Callable[[builtins.int, builtins.int], None]] = None) -> bytes:
        r"""
        Load a file from the device.
        
        ### Arguments
        
        * `name` - The full path of the file on the device.
        * `progress` - A callable object that takes (transmitted, total) values as parameters.
                       Any return value is ignored. Raising an exception aborts the operation.
        
        ### Return
        
        The file content
        
        ### Performance
        
        Downloading files with Zephyr's default parameters is slow.
        You want to increase [`MCUMGR_TRANSPORT_NETBUF_SIZE`](https://github.com/zephyrproject-rtos/zephyr/blob/v4.2.1/subsys/mgmt/mcumgr/transport/Kconfig#L40)
        to maybe `4096` or larger.
        """
    def fs_file_upload(self, name: builtins.str, data: bytes, progress: typing.Optional[collections.abc.Callable[[builtins.int, builtins.int], None]] = None) -> None:
        r"""
        Write a file to the device.
        
        ### Arguments
        
        * `name` - The full path of the file on the device.
        * `data` - The file content.
        * `progress` - A callable object that takes (transmitted, total) values as parameters.
                       Any return value is ignored. Raising an exception aborts the operation.
        
        ### Performance
        
        Uploading files with Zephyr's default parameters is slow.
        You want to increase [`MCUMGR_TRANSPORT_NETBUF_SIZE`](https://github.com/zephyrproject-rtos/zephyr/blob/v4.2.1/subsys/mgmt/mcumgr/transport/Kconfig#L40)
        to maybe `4096` and then enable larger chunking through either `set_frame_size`
        or `use_auto_frame_size`.
        """
    def fs_file_status(self, name: builtins.str) -> FileStatus:
        r"""
        Queries the file status
        """
    def fs_file_checksum(self, name: builtins.str, algorithm: typing.Optional[builtins.str] = None, offset: builtins.int = 0, length: typing.Optional[builtins.int] = None) -> FileChecksum:
        r"""
        Computes the hash/checksum of a file
        
        For available algorithms, see `fs_supported_checksum_types`.
        
        ### Arguments
        
        * `name` - The absolute path of the file on the device
        * `algorithm` - The hash/checksum algorithm to use, or default if None
        * `offset` - How many bytes of the file to skip
        * `length` - How many bytes to read after `offset`. None for the entire file.
        """
    def fs_supported_checksum_types(self) -> builtins.dict[builtins.str, FileChecksumProperties]:
        r"""
        Queries which hash/checksum algorithms are available on the target
        """
    def fs_file_close(self) -> None:
        r"""
        Close all device files MCUmgr has currently open
        """
    def shell_execute(self, argv: typing.Sequence[builtins.str], use_retries: builtins.bool = True) -> builtins.str:
        r"""
        Run a shell command.
        
        ### Arguments
        
        * `argv` - The shell command to be executed.
        * `use_retries` - Retry request a certain amount of times if a transport error occurs.
          Be aware that this might cause the command to be executed multiple times.
        
        ### Return
        
        The command output
        """
    def enum_get_group_count(self) -> builtins.int:
        r"""
        Query how many MCUmgr groups are supported by the device.
        
        ### Return
        
        The number of MCUmgr groups the device supports.
        """
    def enum_get_group_ids(self) -> builtins.list[builtins.int]:
        r"""
        Query all available group IDs in a single command.
        
        Note that this might fail if the amount of groups is too large for the
        SMP frame.
        But given that the Zephyr implementation contains less than 10 groups,
        this is currently highly unlikely.
        
        If it does fail, use `enum_iter_group_ids` to iterate
        through the available group IDs one by one.
        
        ### Return
        
        A list of all MCUmgr group IDs the device supports.
        """
    def enum_get_group_id(self, index: builtins.int) -> builtins.int:
        r"""
        Query a single group ID from the device.
        
        ### Arguments
        
        * `index` - The index in the list of group IDs.
          Must be smaller than `enum_get_group_count`.
        
        ### Return
        
        The group ID of the group with the given index
        """
    def enum_iter_group_ids(self) -> collections.abc.Iterator[builtins.int]:
        r"""
        Iterate through all supported MCUmgr Groups.
        
        Same as `enum_get_group_ids`, but does not
        require large message sizes if the number of groups is large. The tradeoff is
        that this function is much slower.
        """
    def enum_get_group_details(self, groups: typing.Optional[typing.Sequence[builtins.int]] = None) -> builtins.list[GroupDetails]:
        r"""
        Query details from all available groups.
        
        ### Arguments
        
        * `groups` - The group IDs to fetch details for. If omitted, fetch all groups.
        
        ### Return
        
        A list of details about all MCUmgr group IDs the device supports.
        """
    def zephyr_erase_storage(self) -> None:
        r"""
        Erase the `storage_partition` flash partition.
        """
    def raw_command(self, write_operation: builtins.bool, group_id: builtins.int, command_id: builtins.int, data: typing.Any) -> typing.Any:
        r"""
        Execute a raw MCUmgrCommand.
        
        Only returns if no error happened, so the
        user does not need to check for an `rc` or `err`
        field in the response.
        
        Read Zephyr's [SMP Protocol Specification](https://docs.zephyrproject.org/latest/services/device_mgmt/smp_protocol.html)
        for more information.
        
        ### Arguments
        
        * `write_operation` - Whether the command is a read or write operation.
        * `group_id` - The group ID of the command
        * `command_id` - The command ID
        * `data` - Anything that can be serialized as a proper packet payload.
        
        ### Example
        
        ```python
        client.raw_command(True, 0, 0, {"d": "Hello!"})
        # Returns: {'r': 'Hello!'}
        ```
        """
    def __enter__(self) -> MCUmgrClient: ...
    def __exit__(self, _exc_type: typing.Any, _exc_value: typing.Any, _traceback: typing.Any) -> builtins.bool:
        r"""
        Closes the connection
        """

@typing.final
class MCUmgrParameters:
    r"""
    Return value of `MCUmgrClient.os_mcumgr_parameters`.
    """
    @property
    def buf_size(self) -> builtins.int:
        r"""
        Single SMP buffer size, this includes SMP header and CBOR payload
        """
    @property
    def buf_count(self) -> builtins.int:
        r"""
        Number of SMP buffers supported
        """

@typing.final
class McubootImageInfo:
    r"""
    Information about an MCUboot firmware image
    """
    @property
    def version(self) -> builtins.str:
        r"""
        Firmware version
        """
    @property
    def hash(self) -> bytes:
        r"""
        The identifying hash for the firmware
        
        Note that this will not be the same as the SHA256 of the whole file, it is the field in the
        MCUboot TLV section that contains a hash of the data which is used for signature
        verification purposes.
        """

@typing.final
class MemoryPoolStatistics:
    r"""
    Statistics of an MCU memory pool
    """
    @property
    def blksiz(self) -> builtins.int:
        r"""
        size of a memory block in the pool
        """
    @property
    def nblks(self) -> builtins.int:
        r"""
        number of blocks in the pool
        """
    @property
    def nfree(self) -> builtins.int:
        r"""
        number of free blocks
        """
    @property
    def min(self) -> builtins.int:
        r"""
        lowest number of free blocks the pool reached during runtime
        """

@typing.final
class SettingData:
    r"""
    Return value of `MCUmgrClient.settings_read_ext`.
    """
    @property
    def value(self) -> bytes:
        r"""
        The returned data.
        
        Note that the underlying data type cannot be specified through this and
        must be known and parsed by the client.
        """
    @property
    def max_size(self) -> typing.Optional[builtins.int]:
        r"""
        Will be set if the maximum supported data size is smaller than the
        maximum requested data size, and contains the maximum data size
        which the device supports
        """

@typing.final
class SlotInfoImage:
    r"""
    Information about a firmware image type returned by `MCUmgrClient.image_slot_info`
    """
    @property
    def image(self) -> builtins.int:
        r"""
        number of the image
        """
    @property
    def slots(self) -> builtins.list[SlotInfoImageSlot]:
        r"""
        slots available for the image
        """
    @property
    def max_image_size(self) -> typing.Optional[builtins.int]:
        r"""
        maximum size of an application that can be uploaded to that image number
        """

@typing.final
class SlotInfoImageSlot:
    r"""
    Information about a slot that can hold a firmware image
    """
    @property
    def slot(self) -> builtins.int:
        r"""
        slot inside the image being enumerated
        """
    @property
    def size(self) -> builtins.int:
        r"""
        size of the slot
        """
    @property
    def upload_image_id(self) -> typing.Optional[builtins.int]:
        r"""
        specifies the image ID that can be used by external tools to upload an image to that slot
        """

@typing.final
class TaskStatistics:
    r"""
    Statistics of an MCU task/thread
    """
    @property
    def prio(self) -> builtins.int:
        r"""
        task priority
        """
    @property
    def tid(self) -> builtins.int:
        r"""
        numeric task ID
        """
    @property
    def state(self) -> builtins.int:
        r"""
        numeric task state
        """
    @property
    def stkuse(self) -> typing.Optional[builtins.int]:
        r"""
        task’s/thread’s stack usage
        """
    @property
    def stksiz(self) -> typing.Optional[builtins.int]:
        r"""
        task’s/thread’s stack size
        """
    @property
    def cswcnt(self) -> typing.Optional[builtins.int]:
        r"""
        task’s/thread’s context switches
        """
    @property
    def runtime(self) -> typing.Optional[builtins.int]:
        r"""
        task’s/thread’s runtime in “ticks”
        """

@typing.final
class FileChecksumDataFormat(enum.Enum):
    r"""
    Data format of the hash/checksum type
    """
    Numerical = ...
    r"""
    Data is a number
    """
    ByteArray = ...
    r"""
    Data is a bytes array
    """

def mcuboot_get_image_info(image_data: bytes) -> McubootImageInfo:
    r"""
    Extract information from an MCUboot image file
    """

