[package]
name = "mcumgr-toolkit"
description = "Core library of the software suite for Zephyr's MCUmgr protocol"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true

[features]
# Enable the BLE backend
ble = ["dep:btleplug", "dep:tokio", "dep:futures", "dep:uuid"]

# Build libdbus statically from scratch instead of linking to it
vendored-dbus = ["ble", "dep:dbus", "dbus/vendored"]

[target.'cfg(target_os = "linux")'.dependencies]
dbus = { workspace = true, optional = true }
socket2 = { workspace = true, features = ["all"] }
libc.workspace = true

[dependencies]
thiserror.workspace = true
serialport = { workspace = true, features = ["usbportinfo-interface", "serde"] }
miette.workspace = true
rand.workspace = true
base64.workspace = true
crc.workspace = true
sha2.workspace = true
ringbuf.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_bytes.workspace = true
serde_repr.workspace = true
ciborium.workspace = true
log.workspace = true
strum = { workspace = true, features = ["derive"] }
chrono = { workspace = true, features = ["serde"] }
hex = { workspace = true, features = ["serde"] }
regex.workspace = true
polonius-the-crab.workspace = true
btleplug = { workspace = true, optional = true }
tokio = { workspace = true, features = [
    "rt-multi-thread",
    "time",
], optional = true }
futures = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[dev-dependencies]
proptest = "1.11.0"
tokio = { workspace = true, features = ["macros", "test-util"] }

[package.metadata.docs.rs]
features = ["ble"]
